from typing import Protocol
from ..contracts import Observation, ActionChunk, StepResult, Evaluation

class Environment(Protocol):
    def reset(self, seed: int) -> Observation: ...
    def step(self, action: ActionChunk, command_id: str) -> StepResult: ...
    def evaluate(self) -> Evaluation: ...
    def metadata(self) -> dict: ...
    def close(self): ...
